name: Build
on: [push]

env:
  CI_BUILD_NUM: ${{ github.run_id }}
  CI_BRANCH: ${{ github.ref_name }}

permissions:
  contents: write  # semantic-release-dry verifies the write permissions
  issues: read # needed by semantic-release
  pull-requests: write # needed by semantic-release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint the code
        run: npm run lint

      - name: Run the tests
        run: npm run test
      - name: Run the integration tests
        run: npm run test:it
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info

  test-deploy:
    name: Test Deploy
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: test
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: extracting last commit message
        run: |
          echo "CI_LAST_COMMIT_MSG=$(git show -s --format="%s")" >> $GITHUB_ENV
          echo CI_LAST_COMMIT_MSG
      - name: Install dependencies
        run: npm ci
      - name: Branch Deployment
        run: npm run deploy:ci
        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}

      - name: Post-Deployment Integration Test
        run: npm run test:postdeploy
        env:
          IT_IMS_STAGE_ENDPOINT: ${{ secrets.IT_IMS_STAGE_ENDPOINT }}
          IT_IMS_STAGE_CLIENT_ID_LIMITED_USER: ${{ secrets.IT_IMS_STAGE_CLIENT_ID_LIMITED_USER }}
          IT_IMS_STAGE_CLIENT_SECRET_LIMITED_USER: ${{ secrets.IT_IMS_STAGE_CLIENT_SECRET_LIMITED_USER }}
          IT_IMS_STAGE_CLIENT_ID_SUPER_USER: ${{ secrets.IT_IMS_STAGE_CLIENT_ID_SUPER_USER }}
          IT_IMS_STAGE_CLIENT_SECRET_SUPER_USER: ${{ secrets.IT_IMS_STAGE_CLIENT_SECRET_SUPER_USER }}
          IT_IMS_STAGE_SCOPES: ${{ secrets.IT_IMS_STAGE_SCOPES }}
      - name: Semantic Release (Dry Run)
        run: npm run semantic-release-dry
        env:
          GITHUB_TOKEN: ${{ secrets.ADOBE_BOT_GITHUB_TOKEN }}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          token: ${{ secrets.ADOBE_BOT_GITHUB_TOKEN }}
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: extracting last commit message
        run: |
          echo "CI_LAST_COMMIT_MSG=$(git show -s --format="%s")" >> $GITHUB_ENV
          echo CI_LAST_COMMIT_MSG
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.ADOBE_BOT_GITHUB_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          IT_IMS_STAGE_ENDPOINT: ${{ secrets.IT_IMS_STAGE_ENDPOINT }}
          IT_IMS_STAGE_CLIENT_ID_LIMITED_USER: ${{ secrets.IT_IMS_STAGE_CLIENT_ID_LIMITED_USER }}
          IT_IMS_STAGE_CLIENT_SECRET_LIMITED_USER: ${{ secrets.IT_IMS_STAGE_CLIENT_SECRET_LIMITED_USER }}
          IT_IMS_STAGE_CLIENT_ID_SUPER_USER: ${{ secrets.IT_IMS_STAGE_CLIENT_ID_SUPER_USER }}
          IT_IMS_STAGE_CLIENT_SECRET_SUPER_USER: ${{ secrets.IT_IMS_STAGE_CLIENT_SECRET_SUPER_USER }}
          IT_IMS_STAGE_SCOPES: ${{ secrets.IT_IMS_STAGE_SCOPES }}

